################################################################################
# joint states
################################################################################
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

################################################################################
# position controller
################################################################################
position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_elbow_joint
    - l_wrist_1_joint
    - l_wrist_2_joint
    - l_wrist_3_joint
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_elbow_joint
    - r_wrist_1_joint
    - r_wrist_2_joint
    - r_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      l_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      l_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      l_elbow_joint: {trajectory: 0.1, goal: 0.1}
      l_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      l_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      l_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
      r_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      r_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      r_elbow_joint: {trajectory: 0.1, goal: 0.1}
      r_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      r_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      r_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10