std_msgs/Int64 dur
std_msgs/Int32 num_active_ieq
std_msgs/Int32 num_violated_ieq
std_msgs/Int32 conflict

std_msgs/Float64 max_force
std_msgs/Float64 min_distance
std_msgs/Float64 max_proximity

control_core_msgs/Vector distances
control_core_msgs/Vector cell_nums
control_core_msgs/Vector vel_limits
control_core_msgs/Vector vel_cmds
control_core_msgs/Vector acc_limits

std_msgs/Float64 weight
control_core_msgs/Vector a_relaxed
