// Auto-generated. Do not edit!

// (in-package behavior_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class MoveToCartesianMobileManipulatorGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.targets = null;
      this.motion_tasks = null;
      this.period = null;
    }
    else {
      if (initObj.hasOwnProperty('targets')) {
        this.targets = initObj.targets
      }
      else {
        this.targets = new geometry_msgs.msg.PoseArray();
      }
      if (initObj.hasOwnProperty('motion_tasks')) {
        this.motion_tasks = initObj.motion_tasks
      }
      else {
        this.motion_tasks = [];
      }
      if (initObj.hasOwnProperty('period')) {
        this.period = initObj.period
      }
      else {
        this.period = new std_msgs.msg.Float64();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveToCartesianMobileManipulatorGoal
    // Serialize message field [targets]
    bufferOffset = geometry_msgs.msg.PoseArray.serialize(obj.targets, buffer, bufferOffset);
    // Serialize message field [motion_tasks]
    // Serialize the length for message field [motion_tasks]
    bufferOffset = _serializer.uint32(obj.motion_tasks.length, buffer, bufferOffset);
    obj.motion_tasks.forEach((val) => {
      bufferOffset = std_msgs.msg.String.serialize(val, buffer, bufferOffset);
    });
    // Serialize message field [period]
    bufferOffset = std_msgs.msg.Float64.serialize(obj.period, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveToCartesianMobileManipulatorGoal
    let len;
    let data = new MoveToCartesianMobileManipulatorGoal(null);
    // Deserialize message field [targets]
    data.targets = geometry_msgs.msg.PoseArray.deserialize(buffer, bufferOffset);
    // Deserialize message field [motion_tasks]
    // Deserialize array length for message field [motion_tasks]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.motion_tasks = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.motion_tasks[i] = std_msgs.msg.String.deserialize(buffer, bufferOffset)
    }
    // Deserialize message field [period]
    data.period = std_msgs.msg.Float64.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseArray.getMessageSize(object.targets);
    object.motion_tasks.forEach((val) => {
      length += std_msgs.msg.String.getMessageSize(val);
    });
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'behavior_msgs/MoveToCartesianMobileManipulatorGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '68dd2db2f792d0ee848d89b6adce522f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/PoseArray targets  # target poses wrt frame_id in header field
    std_msgs/String[] motion_tasks       # motion task names for the movement
    std_msgs/Float64 period           # time period of the motion
    
    ================================================================================
    MSG: geometry_msgs/PoseArray
    # An array of poses with a header for global reference.
    
    Header header
    
    Pose[] poses
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    ================================================================================
    MSG: std_msgs/Float64
    float64 data
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveToCartesianMobileManipulatorGoal(null);
    if (msg.targets !== undefined) {
      resolved.targets = geometry_msgs.msg.PoseArray.Resolve(msg.targets)
    }
    else {
      resolved.targets = new geometry_msgs.msg.PoseArray()
    }

    if (msg.motion_tasks !== undefined) {
      resolved.motion_tasks = new Array(msg.motion_tasks.length);
      for (let i = 0; i < resolved.motion_tasks.length; ++i) {
        resolved.motion_tasks[i] = std_msgs.msg.String.Resolve(msg.motion_tasks[i]);
      }
    }
    else {
      resolved.motion_tasks = []
    }

    if (msg.period !== undefined) {
      resolved.period = std_msgs.msg.Float64.Resolve(msg.period)
    }
    else {
      resolved.period = new std_msgs.msg.Float64()
    }

    return resolved;
    }
};

module.exports = MoveToCartesianMobileManipulatorGoal;
