// Auto-generated. Do not edit!

// (in-package behavior_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class MoveToCartesianResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.cmd = null;
      this.real = null;
    }
    else {
      if (initObj.hasOwnProperty('cmd')) {
        this.cmd = initObj.cmd
      }
      else {
        this.cmd = new geometry_msgs.msg.PoseStamped();
      }
      if (initObj.hasOwnProperty('real')) {
        this.real = initObj.real
      }
      else {
        this.real = new geometry_msgs.msg.PoseStamped();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveToCartesianResult
    // Serialize message field [cmd]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.cmd, buffer, bufferOffset);
    // Serialize message field [real]
    bufferOffset = geometry_msgs.msg.PoseStamped.serialize(obj.real, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveToCartesianResult
    let len;
    let data = new MoveToCartesianResult(null);
    // Deserialize message field [cmd]
    data.cmd = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    // Deserialize message field [real]
    data.real = geometry_msgs.msg.PoseStamped.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.cmd);
    length += geometry_msgs.msg.PoseStamped.getMessageSize(object.real);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'behavior_msgs/MoveToCartesianResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '5dffad9e3fc5177a0ee928b18ee386b4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    geometry_msgs/PoseStamped cmd
    geometry_msgs/PoseStamped real
    
    ================================================================================
    MSG: geometry_msgs/PoseStamped
    # A Pose with reference coordinate frame and timestamp
    Header header
    Pose pose
    
    ================================================================================
    MSG: std_msgs/Header
    # Standard metadata for higher-level stamped data types.
    # This is generally used to communicate timestamped data 
    # in a particular coordinate frame.
    # 
    # sequence ID: consecutively increasing ID 
    uint32 seq
    #Two-integer timestamp that is expressed as:
    # * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
    # * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
    # time-handling sugar is provided by the client library
    time stamp
    #Frame this data is associated with
    string frame_id
    
    ================================================================================
    MSG: geometry_msgs/Pose
    # A representation of pose in free space, composed of position and orientation. 
    Point position
    Quaternion orientation
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    ================================================================================
    MSG: geometry_msgs/Quaternion
    # This represents an orientation in free space in quaternion form.
    
    float64 x
    float64 y
    float64 z
    float64 w
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveToCartesianResult(null);
    if (msg.cmd !== undefined) {
      resolved.cmd = geometry_msgs.msg.PoseStamped.Resolve(msg.cmd)
    }
    else {
      resolved.cmd = new geometry_msgs.msg.PoseStamped()
    }

    if (msg.real !== undefined) {
      resolved.real = geometry_msgs.msg.PoseStamped.Resolve(msg.real)
    }
    else {
      resolved.real = new geometry_msgs.msg.PoseStamped()
    }

    return resolved;
    }
};

module.exports = MoveToCartesianResult;
