(cl:in-package ics_tsid_task_msgs-msg)
(cl:export '(DUR-VAL
          DUR
          NUM_ACTIVE_IEQ-VAL
          NUM_ACTIVE_IEQ
          NUM_VIOLATED_IEQ-VAL
          NUM_VIOLATED_IEQ
          CONFLICT-VAL
          CONFLICT
          MAX_FORCE-VAL
          MAX_FORCE
          MIN_DISTANCE-VAL
          MIN_DISTANCE
          MAX_PROXIMITY-VAL
          MAX_PROXIMITY
          DISTANCES-VAL
          DISTANCES
          CELL_NUMS-VAL
          CELL_NUMS
          VEL_LIMITS-VAL
          VEL_LIMITS
          VEL_CMDS-VAL
          VEL_CMDS
          ACC_LIMITS-VAL
          ACC_LIMITS
          WEIGHT-VAL
          WEIGHT
          A_RELAXED-VAL
          A_RELAXED
))