// Generated by gencpp from file behavior_msgs/ListBehaviorResponse.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MSGS_MESSAGE_LISTBEHAVIORRESPONSE_H
#define BEHAVIOR_MSGS_MESSAGE_LISTBEHAVIORRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_msgs
{
template <class ContainerAllocator>
struct ListBehaviorResponse_
{
  typedef ListBehaviorResponse_<ContainerAllocator> Type;

  ListBehaviorResponse_()
    : loaded_behaviors()
    , running_behaviors()  {
    }
  ListBehaviorResponse_(const ContainerAllocator& _alloc)
    : loaded_behaviors(_alloc)
    , running_behaviors(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _loaded_behaviors_type;
  _loaded_behaviors_type loaded_behaviors;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _running_behaviors_type;
  _running_behaviors_type running_behaviors;





  typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ListBehaviorResponse_

typedef ::behavior_msgs::ListBehaviorResponse_<std::allocator<void> > ListBehaviorResponse;

typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorResponse > ListBehaviorResponsePtr;
typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorResponse const> ListBehaviorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator1> & lhs, const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.loaded_behaviors == rhs.loaded_behaviors &&
    lhs.running_behaviors == rhs.running_behaviors;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator1> & lhs, const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db7d6a6bd85a4f8fde354aa4e08d9629";
  }

  static const char* value(const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb7d6a6bd85a4f8fULL;
  static const uint64_t static_value2 = 0xde354aa4e08d9629ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_msgs/ListBehaviorResponse";
  }

  static const char* value(const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] loaded_behaviors\n"
"string[] running_behaviors\n"
;
  }

  static const char* value(const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.loaded_behaviors);
      stream.next(m.running_behaviors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListBehaviorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_msgs::ListBehaviorResponse_<ContainerAllocator>& v)
  {
    s << indent << "loaded_behaviors[]" << std::endl;
    for (size_t i = 0; i < v.loaded_behaviors.size(); ++i)
    {
      s << indent << "  loaded_behaviors[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.loaded_behaviors[i]);
    }
    s << indent << "running_behaviors[]" << std::endl;
    for (size_t i = 0; i < v.running_behaviors.size(); ++i)
    {
      s << indent << "  running_behaviors[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.running_behaviors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MSGS_MESSAGE_LISTBEHAVIORRESPONSE_H
