// Generated by gencpp from file behavior_msgs/ListBehaviorRequest.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MSGS_MESSAGE_LISTBEHAVIORREQUEST_H
#define BEHAVIOR_MSGS_MESSAGE_LISTBEHAVIORREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace behavior_msgs
{
template <class ContainerAllocator>
struct ListBehaviorRequest_
{
  typedef ListBehaviorRequest_<ContainerAllocator> Type;

  ListBehaviorRequest_()
    {
    }
  ListBehaviorRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ListBehaviorRequest_

typedef ::behavior_msgs::ListBehaviorRequest_<std::allocator<void> > ListBehaviorRequest;

typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorRequest > ListBehaviorRequestPtr;
typedef boost::shared_ptr< ::behavior_msgs::ListBehaviorRequest const> ListBehaviorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace behavior_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_msgs/ListBehaviorRequest";
  }

  static const char* value(const ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListBehaviorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::behavior_msgs::ListBehaviorRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MSGS_MESSAGE_LISTBEHAVIORREQUEST_H
