// Generated by gencpp from file behavior_msgs/MoveToCartesianActionGoal.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MSGS_MESSAGE_MOVETOCARTESIANACTIONGOAL_H
#define BEHAVIOR_MSGS_MESSAGE_MOVETOCARTESIANACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <behavior_msgs/MoveToCartesianGoal.h>

namespace behavior_msgs
{
template <class ContainerAllocator>
struct MoveToCartesianActionGoal_
{
  typedef MoveToCartesianActionGoal_<ContainerAllocator> Type;

  MoveToCartesianActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  MoveToCartesianActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToCartesianActionGoal_

typedef ::behavior_msgs::MoveToCartesianActionGoal_<std::allocator<void> > MoveToCartesianActionGoal;

typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianActionGoal > MoveToCartesianActionGoalPtr;
typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianActionGoal const> MoveToCartesianActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator1> & lhs, const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator1> & lhs, const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac425a0e74df5c9c679a262744e2bcce";
  }

  static const char* value(const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac425a0e74df5c9cULL;
  static const uint64_t static_value2 = 0x679a262744e2bcceULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_msgs/MoveToCartesianActionGoal";
  }

  static const char* value(const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"MoveToCartesianGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: behavior_msgs/MoveToCartesianGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PoseStamped target  # target pose wrt frame_id in header field\n"
"std_msgs/String motion_task       # motion task for the movement\n"
"std_msgs/Float64 period           # time period of the motion\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToCartesianActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_msgs::MoveToCartesianActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MSGS_MESSAGE_MOVETOCARTESIANACTIONGOAL_H
