// Generated by gencpp from file behavior_msgs/MoveToCartesianGoal.msg
// DO NOT EDIT!


#ifndef BEHAVIOR_MSGS_MESSAGE_MOVETOCARTESIANGOAL_H
#define BEHAVIOR_MSGS_MESSAGE_MOVETOCARTESIANGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>
#include <std_msgs/String.h>
#include <std_msgs/Float64.h>

namespace behavior_msgs
{
template <class ContainerAllocator>
struct MoveToCartesianGoal_
{
  typedef MoveToCartesianGoal_<ContainerAllocator> Type;

  MoveToCartesianGoal_()
    : target()
    , motion_task()
    , period()  {
    }
  MoveToCartesianGoal_(const ContainerAllocator& _alloc)
    : target(_alloc)
    , motion_task(_alloc)
    , period(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_type;
  _target_type target;

   typedef  ::std_msgs::String_<ContainerAllocator>  _motion_task_type;
  _motion_task_type motion_task;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _period_type;
  _period_type period;





  typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToCartesianGoal_

typedef ::behavior_msgs::MoveToCartesianGoal_<std::allocator<void> > MoveToCartesianGoal;

typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianGoal > MoveToCartesianGoalPtr;
typedef boost::shared_ptr< ::behavior_msgs::MoveToCartesianGoal const> MoveToCartesianGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator1> & lhs, const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target == rhs.target &&
    lhs.motion_task == rhs.motion_task &&
    lhs.period == rhs.period;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator1> & lhs, const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace behavior_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a64607e6531d426b71f2d434d7f8905";
  }

  static const char* value(const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a64607e6531d426ULL;
  static const uint64_t static_value2 = 0xb71f2d434d7f8905ULL;
};

template<class ContainerAllocator>
struct DataType< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "behavior_msgs/MoveToCartesianGoal";
  }

  static const char* value(const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/PoseStamped target  # target pose wrt frame_id in header field\n"
"std_msgs/String motion_task       # motion task for the movement\n"
"std_msgs/Float64 period           # time period of the motion\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
;
  }

  static const char* value(const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target);
      stream.next(m.motion_task);
      stream.next(m.period);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToCartesianGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::behavior_msgs::MoveToCartesianGoal_<ContainerAllocator>& v)
  {
    s << indent << "target: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target);
    s << indent << "motion_task: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.motion_task);
    s << indent << "period: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.period);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEHAVIOR_MSGS_MESSAGE_MOVETOCARTESIANGOAL_H
