<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

	<!--Common definitions -->
	<xacro:include filename="$(find tomm_description)/urdf/common.xacro"/>

	<!-- xacro macros Wheels-->
	<xacro:include filename="$(find tomm_description)/urdf/wheels/wheels.urdf.xacro"/>

	<!-- xacro base (includes: base, Logos, Torso, wheels) -->
	<xacro:macro name="tom_base_v0" params="name">

	<!-- Mobile base block  -->
	<link name="${name}_link">
	    <visual>
		    <origin xyz="${base_x_origin} 0 ${base_z_origin}" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}" />
		    <geometry>
		        <mesh filename="package://tomm_description/meshes/base/item_profile.dae"/>       
		    </geometry>
		    <material name="LightGrey"/>
			</visual>
			<collision>
					<geometry>
		        	<mesh filename="package://tomm_description/meshes/base/item_profile_collision.dae" scale="0.001 0.0009 0.001"/>
					</geometry>
					<origin xyz="${base_x_origin + 0.15} ${(base_hight + base_collision_offset)/2 + 0.1} ${base_z_origin - 0.47 - 0.025}" rpy="${90*DEG2RAD} 0 ${-90*DEG2RAD}" />
           <surface>
                <friction>
                <ode>
                    <mu>0</mu>
                    <mu2>0</mu2>
                    <slip1>0</slip1>
                    <slip2>0</slip2>
                </ode>
                </friction>
            </surface>
			</collision> 
			<inertial>
					<origin xyz="${base_x_origin - 0.45} 0 ${base_z_origin - 0.5}" />
					<mass value="${base_frame_mass}"/>
					<inertia ixx="340.82" ixy="0.001" ixz="0.001" iyy="380.20" iyz="0.001" izz="230.54"/>  <!-- inertias are set big to prevent base floating in gazebo -->
					<!-- <inertia ixx="34.82" ixy="0.001" ixz="0.001" iyy="38.20" iyz="0.001" izz="23.54"/> -->
			</inertial>
	</link>

	<!-- Torso link -->
	<link name="torso_link">
	    <visual>
	        <origin xyz="-0.01614 0 -0.76268" rpy="1.57 0 1.57" />
	        <geometry>
	            <mesh filename="package://tomm_description/meshes/base/green_parts.dae"/>       
	        </geometry>
	        <material name="Green"/>
	    </visual>
	    <collision>
	        <geometry>
                <mesh filename="package://tomm_description/meshes/base/green_parts_collision.dae"/>               
	        </geometry>
		    <origin xyz="-0.11 -0.16 -0.8" rpy="${90*DEG2RAD} 0 ${90*DEG2RAD}" />
        </collision>

		<inertial>
		    <origin xyz="0 0 0.44" />
		    <mass value="25"/>
		    <inertia ixx="8.9" ixy="0.017" ixz="0.01" iyy="6.37" iyz="2.2" izz="6.33"/>
		</inertial>
		
	</link>

    <joint name="${name}_to_torso" type="fixed">
        <parent link="${name}_link"/>
        <child link="torso_link"/>
		<origin xyz="${base_x_origin + 0.01614} 0 ${base_z_origin + 0.76268}"/>
	</joint>

	<!-- Wheels-->

	<xacro:wheel parent="${name}_link" prefix="l_front_" reflect="1">
	    <origin xyz="${base_x_origin} 0.303 ${base_z_origin - 0.40}" rpy="-1.57 0 0" />
	</xacro:wheel>

	<xacro:wheel parent="${name}_link" prefix="l_rear_" reflect="1">
	    <origin xyz="${base_x_origin - 0.8115} 0.303 ${base_z_origin - 0.40}" rpy="-1.57 0 0" />
	</xacro:wheel>

	<xacro:wheel parent="${name}_link" prefix="r_front_" reflect="-1">
	    <origin xyz="${base_x_origin} -0.303 ${base_z_origin - 0.40}" rpy="-1.57 0 0" />
	</xacro:wheel>

	<xacro:wheel parent="${name}_link" prefix="r_rear_" reflect="-1">
	    <origin xyz="${base_x_origin - 0.8115} -0.303 ${base_z_origin - 0.40}" rpy="-1.57 0 0" />
	</xacro:wheel>
	
    <!-- Deco Logos-->
    	
	  <link name="ICS_logo_blue_link">
		 <visual>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tomm_description/meshes/base/logo_blue.dae"/>    
		   </geometry>
		 </visual>
		 <collision>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tomm_description/meshes/base/logo_blue.dae"/>    
		   </geometry>
		 </collision>
		</link>

		<joint name="ICS_logo_blue" type="fixed">
		  <parent link="${name}_link"/>
		  <child link="ICS_logo_blue_link"/>
		  <origin xyz="${base_x_origin} 0 ${base_z_origin}"/>
		</joint>

		<link name="ICS_logo_grey_link">
		 <visual>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tomm_description/meshes/base/logo_grey.dae"/>    
		   </geometry>
		 </visual>
		 <collision>
		  <origin xyz="0 0 0" rpy="1.57 0 1.57" />
		   <geometry>
		    <mesh filename="package://tomm_description/meshes/base/logo_grey.dae"/>    
		   </geometry>
		 </collision>
		</link>

		<joint name="ICS_logo_grey" type="fixed">
		  <parent link="${name}_link"/>
		  <child link="ICS_logo_grey_link"/>
		  <origin xyz="${base_x_origin} 0 ${base_z_origin}"/>
		</joint>
		
		
		<!-- xacro macros gazebo-->
		<xacro:include filename="$(find tomm_description)/urdf/base/base.gazebo"/>
        
  </xacro:macro>	
</robot>
