# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_core_msgs/SetCartesianStateGoalRequest.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import control_core_msgs.msg
import geometry_msgs.msg

class SetCartesianStateGoalRequest(genpy.Message):
  _md5sum = "2f3406a57b13431c34e22c35d33bdee4"
  _type = "control_core_msgs/SetCartesianStateGoalRequest"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """CartesianState goal

================================================================================
MSG: control_core_msgs/CartesianState
geometry_msgs/Pose position
geometry_msgs/Twist velocity
geometry_msgs/Accel acceleration
================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Accel
# This expresses acceleration in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular
"""
  __slots__ = ['goal']
  _slot_types = ['control_core_msgs/CartesianState']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       goal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetCartesianStateGoalRequest, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.goal is None:
        self.goal = control_core_msgs.msg.CartesianState()
    else:
      self.goal = control_core_msgs.msg.CartesianState()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_19d().pack(_x.goal.position.position.x, _x.goal.position.position.y, _x.goal.position.position.z, _x.goal.position.orientation.x, _x.goal.position.orientation.y, _x.goal.position.orientation.z, _x.goal.position.orientation.w, _x.goal.velocity.linear.x, _x.goal.velocity.linear.y, _x.goal.velocity.linear.z, _x.goal.velocity.angular.x, _x.goal.velocity.angular.y, _x.goal.velocity.angular.z, _x.goal.acceleration.linear.x, _x.goal.acceleration.linear.y, _x.goal.acceleration.linear.z, _x.goal.acceleration.angular.x, _x.goal.acceleration.angular.y, _x.goal.acceleration.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal is None:
        self.goal = control_core_msgs.msg.CartesianState()
      end = 0
      _x = self
      start = end
      end += 152
      (_x.goal.position.position.x, _x.goal.position.position.y, _x.goal.position.position.z, _x.goal.position.orientation.x, _x.goal.position.orientation.y, _x.goal.position.orientation.z, _x.goal.position.orientation.w, _x.goal.velocity.linear.x, _x.goal.velocity.linear.y, _x.goal.velocity.linear.z, _x.goal.velocity.angular.x, _x.goal.velocity.angular.y, _x.goal.velocity.angular.z, _x.goal.acceleration.linear.x, _x.goal.acceleration.linear.y, _x.goal.acceleration.linear.z, _x.goal.acceleration.angular.x, _x.goal.acceleration.angular.y, _x.goal.acceleration.angular.z,) = _get_struct_19d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_19d().pack(_x.goal.position.position.x, _x.goal.position.position.y, _x.goal.position.position.z, _x.goal.position.orientation.x, _x.goal.position.orientation.y, _x.goal.position.orientation.z, _x.goal.position.orientation.w, _x.goal.velocity.linear.x, _x.goal.velocity.linear.y, _x.goal.velocity.linear.z, _x.goal.velocity.angular.x, _x.goal.velocity.angular.y, _x.goal.velocity.angular.z, _x.goal.acceleration.linear.x, _x.goal.acceleration.linear.y, _x.goal.acceleration.linear.z, _x.goal.acceleration.angular.x, _x.goal.acceleration.angular.y, _x.goal.acceleration.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.goal is None:
        self.goal = control_core_msgs.msg.CartesianState()
      end = 0
      _x = self
      start = end
      end += 152
      (_x.goal.position.position.x, _x.goal.position.position.y, _x.goal.position.position.z, _x.goal.position.orientation.x, _x.goal.position.orientation.y, _x.goal.position.orientation.z, _x.goal.position.orientation.w, _x.goal.velocity.linear.x, _x.goal.velocity.linear.y, _x.goal.velocity.linear.z, _x.goal.velocity.angular.x, _x.goal.velocity.angular.y, _x.goal.velocity.angular.z, _x.goal.acceleration.linear.x, _x.goal.acceleration.linear.y, _x.goal.acceleration.linear.z, _x.goal.acceleration.angular.x, _x.goal.acceleration.angular.y, _x.goal.acceleration.angular.z,) = _get_struct_19d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_19d = None
def _get_struct_19d():
    global _struct_19d
    if _struct_19d is None:
        _struct_19d = struct.Struct("<19d")
    return _struct_19d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_core_msgs/SetCartesianStateGoalResponse.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class SetCartesianStateGoalResponse(genpy.Message):
  _md5sum = "d41d8cd98f00b204e9800998ecf8427e"
  _type = "control_core_msgs/SetCartesianStateGoalResponse"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """"""
  __slots__ = []
  _slot_types = []

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SetCartesianStateGoalResponse, self).__init__(*args, **kwds)

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      pass
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
class SetCartesianStateGoal(object):
  _type          = 'control_core_msgs/SetCartesianStateGoal'
  _md5sum = '2f3406a57b13431c34e22c35d33bdee4'
  _request_class  = SetCartesianStateGoalRequest
  _response_class = SetCartesianStateGoalResponse
