// Generated by gencpp from file walking_core_msgs/PlanFootstepsResponse.msg
// DO NOT EDIT!


#ifndef WALKING_CORE_MSGS_MESSAGE_PLANFOOTSTEPSRESPONSE_H
#define WALKING_CORE_MSGS_MESSAGE_PLANFOOTSTEPSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace walking_core_msgs
{
template <class ContainerAllocator>
struct PlanFootstepsResponse_
{
  typedef PlanFootstepsResponse_<ContainerAllocator> Type;

  PlanFootstepsResponse_()
    : success()  {
    }
  PlanFootstepsResponse_(const ContainerAllocator& _alloc)
    : success(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanFootstepsResponse_

typedef ::walking_core_msgs::PlanFootstepsResponse_<std::allocator<void> > PlanFootstepsResponse;

typedef boost::shared_ptr< ::walking_core_msgs::PlanFootstepsResponse > PlanFootstepsResponsePtr;
typedef boost::shared_ptr< ::walking_core_msgs::PlanFootstepsResponse const> PlanFootstepsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator1> & lhs, const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator1> & lhs, const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace walking_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f31cb2e813cfb0e488c574c3b5d9dbe";
  }

  static const char* value(const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f31cb2e813cfb0eULL;
  static const uint64_t static_value2 = 0x488c574c3b5d9dbeULL;
};

template<class ContainerAllocator>
struct DataType< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "walking_core_msgs/PlanFootstepsResponse";
  }

  static const char* value(const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Bool success\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Bool\n"
"bool data\n"
;
  }

  static const char* value(const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanFootstepsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::walking_core_msgs::PlanFootstepsResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WALKING_CORE_MSGS_MESSAGE_PLANFOOTSTEPSRESPONSE_H
