// Generated by gencpp from file walking_core_msgs/PlanFootsteps.msg
// DO NOT EDIT!


#ifndef WALKING_CORE_MSGS_MESSAGE_PLANFOOTSTEPS_H
#define WALKING_CORE_MSGS_MESSAGE_PLANFOOTSTEPS_H

#include <ros/service_traits.h>


#include <walking_core_msgs/PlanFootstepsRequest.h>
#include <walking_core_msgs/PlanFootstepsResponse.h>


namespace walking_core_msgs
{

struct PlanFootsteps
{

typedef PlanFootstepsRequest Request;
typedef PlanFootstepsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PlanFootsteps
} // namespace walking_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::walking_core_msgs::PlanFootsteps > {
  static const char* value()
  {
    return "6b7b78d5ced6128d564af0ca90b3d6e2";
  }

  static const char* value(const ::walking_core_msgs::PlanFootsteps&) { return value(); }
};

template<>
struct DataType< ::walking_core_msgs::PlanFootsteps > {
  static const char* value()
  {
    return "walking_core_msgs/PlanFootsteps";
  }

  static const char* value(const ::walking_core_msgs::PlanFootsteps&) { return value(); }
};


// service_traits::MD5Sum< ::walking_core_msgs::PlanFootstepsRequest> should match
// service_traits::MD5Sum< ::walking_core_msgs::PlanFootsteps >
template<>
struct MD5Sum< ::walking_core_msgs::PlanFootstepsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::walking_core_msgs::PlanFootsteps >::value();
  }
  static const char* value(const ::walking_core_msgs::PlanFootstepsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::walking_core_msgs::PlanFootstepsRequest> should match
// service_traits::DataType< ::walking_core_msgs::PlanFootsteps >
template<>
struct DataType< ::walking_core_msgs::PlanFootstepsRequest>
{
  static const char* value()
  {
    return DataType< ::walking_core_msgs::PlanFootsteps >::value();
  }
  static const char* value(const ::walking_core_msgs::PlanFootstepsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::walking_core_msgs::PlanFootstepsResponse> should match
// service_traits::MD5Sum< ::walking_core_msgs::PlanFootsteps >
template<>
struct MD5Sum< ::walking_core_msgs::PlanFootstepsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::walking_core_msgs::PlanFootsteps >::value();
  }
  static const char* value(const ::walking_core_msgs::PlanFootstepsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::walking_core_msgs::PlanFootstepsResponse> should match
// service_traits::DataType< ::walking_core_msgs::PlanFootsteps >
template<>
struct DataType< ::walking_core_msgs::PlanFootstepsResponse>
{
  static const char* value()
  {
    return DataType< ::walking_core_msgs::PlanFootsteps >::value();
  }
  static const char* value(const ::walking_core_msgs::PlanFootstepsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WALKING_CORE_MSGS_MESSAGE_PLANFOOTSTEPS_H
