(cl:defpackage control_core_msgs-srv
  (:use )
  (:export
   "COMPUTECONTROL"
   "<COMPUTECONTROL-REQUEST>"
   "COMPUTECONTROL-REQUEST"
   "<COMPUTECONTROL-RESPONSE>"
   "COMPUTECONTROL-RESPONSE"
   "SETCARTESIANPOSITIONGOAL"
   "<SETCARTESIANPOSITIONGOAL-REQUEST>"
   "SETCARTESIANPOSITIONGOAL-REQUEST"
   "<SETCARTESIANPOSITIONGOAL-RESPONSE>"
   "SETCARTESIANPOSITIONGOAL-RESPONSE"
   "SETCARTESIANSTATEGOAL"
   "<SETCARTESIANSTATEGOAL-REQUEST>"
   "SETCARTESIANSTATEGOAL-REQUEST"
   "<SETCARTESIANSTATEGOAL-RESPONSE>"
   "SETCARTESIANSTATEGOAL-RESPONSE"
   "STARTCONTROL"
   "<STARTCONTROL-REQUEST>"
   "STARTCONTROL-REQUEST"
   "<STARTCONTROL-RESPONSE>"
   "STARTCONTROL-RESPONSE"
  ))

