# ordered lists of patch configs
skin_patch_id_config:

 # patch file names (ommitting .xml file type)
 filenames: [
   'rightHand_IndexDistralBack_PatchExtTF', 'rightHand_IndexDistralFront_PatchExtTF',
   'rightHand_IndexMidBack_PatchExtTF', 'rightHand_IndexMidFront_PatchExtTF',
   'rightHand_IndexProximalBack_PatchExtTF', 'rightHand_IndexProximalFront_PatchExtTF',

   'rightHand_MiddleDistralBack_PatchExtTF', 'rightHand_MiddleDistralFront_PatchExtTF',
   'rightHand_MiddleMidBack_PatchExtTF', 'rightHand_MiddleMidFront_PatchExtTF',
   'rightHand_MiddleProximalBack_PatchExtTF', 'rightHand_MiddleProximalFront_PatchExtTF',

   'rightHand_RingDistralBack_PatchExtTF', 'rightHand_RingDistralFront_PatchExtTF',
   'rightHand_RingMidBack_PatchExtTF', 'rightHand_RingMidFront_PatchExtTF',
   'rightHand_RingProximalBack_PatchExtTF', 'rightHand_RingProximalFront_PatchExtTF',

   'rightHand_ThumbDistralBack_PatchExtTF', 'rightHand_ThumbDistralFront_PatchExtTF',
   'rightHand_ThumbDistralMidBack_PatchExtTF', 'rightHand_ThumbDistralMidFront_PatchExtTF',
   'rightHand_ThumbMidBack_PatchExtTF', 'rightHand_ThumbMidFront_PatchExtTF',

   'rightHand_PalmBack_PatchExtTF', 'rightHand_PalmFront_PatchExtTF',
   'rightHand_PalmLeftBack_PatchExtTF',
   'rightHand_PalmRightBack_PatchExtTF',
 ]

 # ids to assign to patches
 ids: [
   200, 201,
   202, 203,
   204, 205,

   206, 207,
   208, 209,
   210, 211,

   212, 213,
   214, 215,
   216, 217,

   218, 219,
   220, 221,
   222, 223,

   224, 225,
   226,
   228,
 ]
