<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

	<!--Common definitions -->
	<xacro:include filename="$(find tomm_description)/urdf/common.xacro"/>
	
	<!-- xacro hands (right_hand=true -> right hand, false -> left hand -->
	<xacro:macro name="tom_no_hand" params="right_hand">
		<xacro:property name="base_link_z" value="0.095" />
		<xacro:property name="DEG2RAD" value="0.01745329251" />
		<xacro:unless value="${right_hand}">
			<link name="l_hand_base_link">
				<visual>
					<geometry>
						<mesh filename="package://tomm_description/meshes/hand/base_link_left.STL" />
					</geometry>
				
					<!-- LEFT -->
					<origin rpy="${-90*DEG2RAD} 0 0" xyz="0 0 0 "/>
					<!-- RIGHT -->
					<!--<origin rpy="0 0 0" xyz="0 0 0 "/>-->
				
					<material name="black">
						<color rgba="0.2 0.2 0.2 1"/>
					</material>
				</visual>
				
				<collision>
					<origin rpy="0 0 0" xyz="-0.009300 0 -${base_link_z/2}"/>
					<geometry>
						<box size="0.0408 0.1130 ${base_link_z}"/>
					</geometry>
				</collision>
				
				<inertial>
					<origin xyz="0 0 ${base_link_z/2}" rpy="0 0 0"/>
					<mass value="0.4154"/>
					<inertia
						ixx="1e-4" ixy="0.0" ixz="0.0"
						iyy="1e-4" iyz="0.0"
						izz="1e-4"/>
				</inertial>
			</link>

			<joint name="l_hand_base_joint" type="fixed">
				<parent link="l_hand_base_adapter_link"/>
				<child link="l_hand_base_link"/>
				<origin xyz="0.01 0 0.095" rpy="0 0 0"/>
  			</joint>
		</xacro:unless>
		<xacro:if value="${right_hand}">
		
			<link name="r_hand_base_link">
				<visual>
						<geometry>
							<mesh filename="package://tomm_description/meshes/hand/base_link.STL" />
						</geometry>
						
					<origin rpy="0 0 0" xyz="0 0 0 "/>

					<material name="black">
							<color rgba="0.2 0.2 0.2 1"/>
						</material>
				</visual>
				
					<collision>
						<origin rpy="0 0 0" xyz="-0.009300 0 -${base_link_z/2}"/>
						<geometry>
							<box size="0.0408 0.1130 ${base_link_z}"/>
						</geometry>
					</collision>

					<inertial>
					<origin xyz="0 0 ${base_link_z/2}" rpy="0 0 0"/>
					<mass value="0.4154"/>
					<inertia
						ixx="1e-4" ixy="0.0" ixz="0.0"
						iyy="1e-4" iyz="0.0"
						izz="1e-4"/>
					</inertial>
			
			</link>
			<joint name="r_hand_base_joint" type="fixed">
				<parent link="r_hand_base_adapter_link"/>
				<child link="r_hand_base_link"/>
				<origin xyz="0.01 0 0.095" rpy="0 0 0"/>
  			</joint>	
		</xacro:if>

  </xacro:macro>	

	


</robot>
