# ordered lists of patch configs (for adding dh trafos)
skin_patch_dh_config:

 # patch file names (ommitting .xml file type)
 filenames: [
   'leftWrist1PatchExtTFId','leftWrist2PatchExtTFId','leftWrist3PatchExtTFId',
   'leftGripperRingPatchExtTFId', 'leftGripperPalmPatchExtTFId'
 ]
 
 # dh frame names
 dh_frames: [
   'l_arm_joint_3', 'l_arm_joint_4', 'l_arm_joint_5',
   'l_arm_joint_6', 'l_arm_joint_6'
 ]

 # parameter names for urdf links wrt dh links in 'tstatic_URDFi_linki.yaml'
 dh_params: [
   '~arm/joint_3', '~arm/joint_4', '~arm/joint_5',
   '~gripper/palm', '~gripper/palm'
 ]

