// Generated by gencpp from file control_core_msgs/AngularState.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_ANGULARSTATE_H
#define CONTROL_CORE_MSGS_MESSAGE_ANGULARSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Quaternion.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace control_core_msgs
{
template <class ContainerAllocator>
struct AngularState_
{
  typedef AngularState_<ContainerAllocator> Type;

  AngularState_()
    : position()
    , velocity()
    , acceleration()  {
    }
  AngularState_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , velocity(_alloc)
    , acceleration(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Quaternion_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _acceleration_type;
  _acceleration_type acceleration;





  typedef boost::shared_ptr< ::control_core_msgs::AngularState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_core_msgs::AngularState_<ContainerAllocator> const> ConstPtr;

}; // struct AngularState_

typedef ::control_core_msgs::AngularState_<std::allocator<void> > AngularState;

typedef boost::shared_ptr< ::control_core_msgs::AngularState > AngularStatePtr;
typedef boost::shared_ptr< ::control_core_msgs::AngularState const> AngularStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_core_msgs::AngularState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_core_msgs::AngularState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_core_msgs::AngularState_<ContainerAllocator1> & lhs, const ::control_core_msgs::AngularState_<ContainerAllocator2> & rhs)
{
  return lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.acceleration == rhs.acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_core_msgs::AngularState_<ContainerAllocator1> & lhs, const ::control_core_msgs::AngularState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::AngularState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::AngularState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::AngularState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::AngularState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::AngularState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::AngularState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_core_msgs::AngularState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e1d5f76ab83eb7ee7b25ee90215e8d1";
  }

  static const char* value(const ::control_core_msgs::AngularState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e1d5f76ab83eb7eULL;
  static const uint64_t static_value2 = 0xe7b25ee90215e8d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_core_msgs::AngularState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_core_msgs/AngularState";
  }

  static const char* value(const ::control_core_msgs::AngularState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_core_msgs::AngularState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Quaternion position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::control_core_msgs::AngularState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_core_msgs::AngularState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AngularState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_core_msgs::AngularState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_core_msgs::AngularState_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "acceleration: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_ANGULARSTATE_H
