// Generated by gencpp from file control_core_msgs/RobotState.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_ROBOTSTATE_H
#define CONTROL_CORE_MSGS_MESSAGE_ROBOTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <control_core_msgs/JointState.h>
#include <control_core_msgs/CartesianState.h>
#include <sensor_msgs/Imu.h>
#include <geometry_msgs/WrenchStamped.h>
#include <control_core_msgs/SkinPatch.h>

namespace control_core_msgs
{
template <class ContainerAllocator>
struct RobotState_
{
  typedef RobotState_<ContainerAllocator> Type;

  RobotState_()
    : joints()
    , floating_base()
    , imu()
    , ft_sensors()
    , patches()  {
    }
  RobotState_(const ContainerAllocator& _alloc)
    : joints(_alloc)
    , floating_base(_alloc)
    , imu(_alloc)
    , ft_sensors(_alloc)
    , patches(_alloc)  {
  (void)_alloc;
    }



   typedef  ::control_core_msgs::JointState_<ContainerAllocator>  _joints_type;
  _joints_type joints;

   typedef  ::control_core_msgs::CartesianState_<ContainerAllocator>  _floating_base_type;
  _floating_base_type floating_base;

   typedef  ::sensor_msgs::Imu_<ContainerAllocator>  _imu_type;
  _imu_type imu;

   typedef std::vector< ::geometry_msgs::WrenchStamped_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >> _ft_sensors_type;
  _ft_sensors_type ft_sensors;

   typedef std::vector< ::control_core_msgs::SkinPatch_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::control_core_msgs::SkinPatch_<ContainerAllocator> >> _patches_type;
  _patches_type patches;





  typedef boost::shared_ptr< ::control_core_msgs::RobotState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_core_msgs::RobotState_<ContainerAllocator> const> ConstPtr;

}; // struct RobotState_

typedef ::control_core_msgs::RobotState_<std::allocator<void> > RobotState;

typedef boost::shared_ptr< ::control_core_msgs::RobotState > RobotStatePtr;
typedef boost::shared_ptr< ::control_core_msgs::RobotState const> RobotStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_core_msgs::RobotState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_core_msgs::RobotState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_core_msgs::RobotState_<ContainerAllocator1> & lhs, const ::control_core_msgs::RobotState_<ContainerAllocator2> & rhs)
{
  return lhs.joints == rhs.joints &&
    lhs.floating_base == rhs.floating_base &&
    lhs.imu == rhs.imu &&
    lhs.ft_sensors == rhs.ft_sensors &&
    lhs.patches == rhs.patches;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_core_msgs::RobotState_<ContainerAllocator1> & lhs, const ::control_core_msgs::RobotState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::RobotState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::RobotState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::RobotState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::RobotState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::RobotState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_core_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c93ef624511e3a3594ee3528444b88cf";
  }

  static const char* value(const ::control_core_msgs::RobotState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc93ef624511e3a35ULL;
  static const uint64_t static_value2 = 0x94ee3528444b88cfULL;
};

template<class ContainerAllocator>
struct DataType< ::control_core_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_core_msgs/RobotState";
  }

  static const char* value(const ::control_core_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_core_msgs::RobotState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "JointState joints\n"
"CartesianState floating_base\n"
"sensor_msgs/Imu imu\n"
"geometry_msgs/WrenchStamped[] ft_sensors\n"
"SkinPatch[] patches\n"
"================================================================================\n"
"MSG: control_core_msgs/JointState\n"
"Vector position\n"
"Vector velocity\n"
"Vector acceleration\n"
"================================================================================\n"
"MSG: control_core_msgs/Vector\n"
"float64[] data\n"
"================================================================================\n"
"MSG: control_core_msgs/CartesianState\n"
"geometry_msgs/Pose position\n"
"geometry_msgs/Twist velocity\n"
"geometry_msgs/Accel acceleration\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Accel\n"
"# This expresses acceleration in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/Imu\n"
"# This is a message to hold data from an IMU (Inertial Measurement Unit)\n"
"#\n"
"# Accelerations should be in m/s^2 (not in g's), and rotational velocity should be in rad/sec\n"
"#\n"
"# If the covariance of the measurement is known, it should be filled in (if all you know is the \n"
"# variance of each measurement, e.g. from the datasheet, just put those along the diagonal)\n"
"# A covariance matrix of all zeros will be interpreted as \"covariance unknown\", and to use the\n"
"# data a covariance will have to be assumed or gotten from some other source\n"
"#\n"
"# If you have no estimate for one of the data elements (e.g. your IMU doesn't produce an orientation \n"
"# estimate), please set element 0 of the associated covariance matrix to -1\n"
"# If you are interpreting this message, please check for a value of -1 in the first element of each \n"
"# covariance matrix, and disregard the associated estimate.\n"
"\n"
"Header header\n"
"\n"
"geometry_msgs/Quaternion orientation\n"
"float64[9] orientation_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 angular_velocity\n"
"float64[9] angular_velocity_covariance # Row major about x, y, z axes\n"
"\n"
"geometry_msgs/Vector3 linear_acceleration\n"
"float64[9] linear_acceleration_covariance # Row major x, y z \n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/WrenchStamped\n"
"# A wrench with reference coordinate frame and timestamp\n"
"Header header\n"
"Wrench wrench\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Wrench\n"
"# This represents force in free space, separated into\n"
"# its linear and angular parts.\n"
"Vector3  force\n"
"Vector3  torque\n"
"\n"
"================================================================================\n"
"MSG: control_core_msgs/SkinPatch\n"
"std_msgs/Header header\n"
"geometry_msgs/Pose pose\n"
"SkinModality force\n"
"SkinModality proximity\n"
"std_msgs/Float64 min_dist\n"
"std_msgs/Float64 max_dist\n"
"================================================================================\n"
"MSG: control_core_msgs/SkinModality\n"
"std_msgs/Float64 min\n"
"std_msgs/Float64 max\n"
"std_msgs/Float64 area\n"
"geometry_msgs/Point cop\n"
"geometry_msgs/Wrench wrench\n"
"geometry_msgs/Polygon hull\n"
"================================================================================\n"
"MSG: std_msgs/Float64\n"
"float64 data\n"
"================================================================================\n"
"MSG: geometry_msgs/Polygon\n"
"#A specification of a polygon where the first and last points are assumed to be connected\n"
"Point32[] points\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::control_core_msgs::RobotState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_core_msgs::RobotState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joints);
      stream.next(m.floating_base);
      stream.next(m.imu);
      stream.next(m.ft_sensors);
      stream.next(m.patches);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_core_msgs::RobotState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_core_msgs::RobotState_<ContainerAllocator>& v)
  {
    s << indent << "joints: ";
    s << std::endl;
    Printer< ::control_core_msgs::JointState_<ContainerAllocator> >::stream(s, indent + "  ", v.joints);
    s << indent << "floating_base: ";
    s << std::endl;
    Printer< ::control_core_msgs::CartesianState_<ContainerAllocator> >::stream(s, indent + "  ", v.floating_base);
    s << indent << "imu: ";
    s << std::endl;
    Printer< ::sensor_msgs::Imu_<ContainerAllocator> >::stream(s, indent + "  ", v.imu);
    s << indent << "ft_sensors[]" << std::endl;
    for (size_t i = 0; i < v.ft_sensors.size(); ++i)
    {
      s << indent << "  ft_sensors[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::WrenchStamped_<ContainerAllocator> >::stream(s, indent + "    ", v.ft_sensors[i]);
    }
    s << indent << "patches[]" << std::endl;
    for (size_t i = 0; i < v.patches.size(); ++i)
    {
      s << indent << "  patches[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::control_core_msgs::SkinPatch_<ContainerAllocator> >::stream(s, indent + "    ", v.patches[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_ROBOTSTATE_H
