// Generated by gencpp from file control_core_msgs/SetCartesianPositionGoal.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_SETCARTESIANPOSITIONGOAL_H
#define CONTROL_CORE_MSGS_MESSAGE_SETCARTESIANPOSITIONGOAL_H

#include <ros/service_traits.h>


#include <control_core_msgs/SetCartesianPositionGoalRequest.h>
#include <control_core_msgs/SetCartesianPositionGoalResponse.h>


namespace control_core_msgs
{

struct SetCartesianPositionGoal
{

typedef SetCartesianPositionGoalRequest Request;
typedef SetCartesianPositionGoalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCartesianPositionGoal
} // namespace control_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::control_core_msgs::SetCartesianPositionGoal > {
  static const char* value()
  {
    return "313b76aa4f010582b3257488c62ac366";
  }

  static const char* value(const ::control_core_msgs::SetCartesianPositionGoal&) { return value(); }
};

template<>
struct DataType< ::control_core_msgs::SetCartesianPositionGoal > {
  static const char* value()
  {
    return "control_core_msgs/SetCartesianPositionGoal";
  }

  static const char* value(const ::control_core_msgs::SetCartesianPositionGoal&) { return value(); }
};


// service_traits::MD5Sum< ::control_core_msgs::SetCartesianPositionGoalRequest> should match
// service_traits::MD5Sum< ::control_core_msgs::SetCartesianPositionGoal >
template<>
struct MD5Sum< ::control_core_msgs::SetCartesianPositionGoalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::control_core_msgs::SetCartesianPositionGoal >::value();
  }
  static const char* value(const ::control_core_msgs::SetCartesianPositionGoalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_core_msgs::SetCartesianPositionGoalRequest> should match
// service_traits::DataType< ::control_core_msgs::SetCartesianPositionGoal >
template<>
struct DataType< ::control_core_msgs::SetCartesianPositionGoalRequest>
{
  static const char* value()
  {
    return DataType< ::control_core_msgs::SetCartesianPositionGoal >::value();
  }
  static const char* value(const ::control_core_msgs::SetCartesianPositionGoalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::control_core_msgs::SetCartesianPositionGoalResponse> should match
// service_traits::MD5Sum< ::control_core_msgs::SetCartesianPositionGoal >
template<>
struct MD5Sum< ::control_core_msgs::SetCartesianPositionGoalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::control_core_msgs::SetCartesianPositionGoal >::value();
  }
  static const char* value(const ::control_core_msgs::SetCartesianPositionGoalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_core_msgs::SetCartesianPositionGoalResponse> should match
// service_traits::DataType< ::control_core_msgs::SetCartesianPositionGoal >
template<>
struct DataType< ::control_core_msgs::SetCartesianPositionGoalResponse>
{
  static const char* value()
  {
    return DataType< ::control_core_msgs::SetCartesianPositionGoal >::value();
  }
  static const char* value(const ::control_core_msgs::SetCartesianPositionGoalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_SETCARTESIANPOSITIONGOAL_H
