// Generated by gencpp from file control_core_msgs/SetCartesianPositionGoalRequest.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_SETCARTESIANPOSITIONGOALREQUEST_H
#define CONTROL_CORE_MSGS_MESSAGE_SETCARTESIANPOSITIONGOALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace control_core_msgs
{
template <class ContainerAllocator>
struct SetCartesianPositionGoalRequest_
{
  typedef SetCartesianPositionGoalRequest_<ContainerAllocator> Type;

  SetCartesianPositionGoalRequest_()
    : goal()  {
    }
  SetCartesianPositionGoalRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCartesianPositionGoalRequest_

typedef ::control_core_msgs::SetCartesianPositionGoalRequest_<std::allocator<void> > SetCartesianPositionGoalRequest;

typedef boost::shared_ptr< ::control_core_msgs::SetCartesianPositionGoalRequest > SetCartesianPositionGoalRequestPtr;
typedef boost::shared_ptr< ::control_core_msgs::SetCartesianPositionGoalRequest const> SetCartesianPositionGoalRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator1> & lhs, const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator2> & rhs)
{
  return lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator1> & lhs, const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace control_core_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "313b76aa4f010582b3257488c62ac366";
  }

  static const char* value(const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x313b76aa4f010582ULL;
  static const uint64_t static_value2 = 0xb3257488c62ac366ULL;
};

template<class ContainerAllocator>
struct DataType< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_core_msgs/SetCartesianPositionGoalRequest";
  }

  static const char* value(const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose goal\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCartesianPositionGoalRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_core_msgs::SetCartesianPositionGoalRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_SETCARTESIANPOSITIONGOALREQUEST_H
