// Generated by gencpp from file control_core_msgs/StartControl.msg
// DO NOT EDIT!


#ifndef CONTROL_CORE_MSGS_MESSAGE_STARTCONTROL_H
#define CONTROL_CORE_MSGS_MESSAGE_STARTCONTROL_H

#include <ros/service_traits.h>


#include <control_core_msgs/StartControlRequest.h>
#include <control_core_msgs/StartControlResponse.h>


namespace control_core_msgs
{

struct StartControl
{

typedef StartControlRequest Request;
typedef StartControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StartControl
} // namespace control_core_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::control_core_msgs::StartControl > {
  static const char* value()
  {
    return "adb9278d966383f41d079c269f203a93";
  }

  static const char* value(const ::control_core_msgs::StartControl&) { return value(); }
};

template<>
struct DataType< ::control_core_msgs::StartControl > {
  static const char* value()
  {
    return "control_core_msgs/StartControl";
  }

  static const char* value(const ::control_core_msgs::StartControl&) { return value(); }
};


// service_traits::MD5Sum< ::control_core_msgs::StartControlRequest> should match
// service_traits::MD5Sum< ::control_core_msgs::StartControl >
template<>
struct MD5Sum< ::control_core_msgs::StartControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::control_core_msgs::StartControl >::value();
  }
  static const char* value(const ::control_core_msgs::StartControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_core_msgs::StartControlRequest> should match
// service_traits::DataType< ::control_core_msgs::StartControl >
template<>
struct DataType< ::control_core_msgs::StartControlRequest>
{
  static const char* value()
  {
    return DataType< ::control_core_msgs::StartControl >::value();
  }
  static const char* value(const ::control_core_msgs::StartControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::control_core_msgs::StartControlResponse> should match
// service_traits::MD5Sum< ::control_core_msgs::StartControl >
template<>
struct MD5Sum< ::control_core_msgs::StartControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::control_core_msgs::StartControl >::value();
  }
  static const char* value(const ::control_core_msgs::StartControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::control_core_msgs::StartControlResponse> should match
// service_traits::DataType< ::control_core_msgs::StartControl >
template<>
struct DataType< ::control_core_msgs::StartControlResponse>
{
  static const char* value()
  {
    return DataType< ::control_core_msgs::StartControl >::value();
  }
  static const char* value(const ::control_core_msgs::StartControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CONTROL_CORE_MSGS_MESSAGE_STARTCONTROL_H
