# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from tomm_hardware_real/OmniBaseState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import tomm_hardware_real.msg

class OmniBaseState(genpy.Message):
  _md5sum = "fc9f3e21e19731c56a4c57b6a5b80bb7"
  _type = "tomm_hardware_real/OmniBaseState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """DriverState[] state
================================================================================
MSG: tomm_hardware_real/DriverState
int32 position
uint32 digital_inputs
int32 velocity
uint16 status"""
  __slots__ = ['state']
  _slot_types = ['tomm_hardware_real/DriverState[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(OmniBaseState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = []
    else:
      self.state = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.state:
        _x = val1
        buff.write(_get_struct_iIiH().pack(_x.position, _x.digital_inputs, _x.velocity, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state = []
      for i in range(0, length):
        val1 = tomm_hardware_real.msg.DriverState()
        _x = val1
        start = end
        end += 14
        (_x.position, _x.digital_inputs, _x.velocity, _x.status,) = _get_struct_iIiH().unpack(str[start:end])
        self.state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.state)
      buff.write(_struct_I.pack(length))
      for val1 in self.state:
        _x = val1
        buff.write(_get_struct_iIiH().pack(_x.position, _x.digital_inputs, _x.velocity, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.state is None:
        self.state = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.state = []
      for i in range(0, length):
        val1 = tomm_hardware_real.msg.DriverState()
        _x = val1
        start = end
        end += 14
        (_x.position, _x.digital_inputs, _x.velocity, _x.status,) = _get_struct_iIiH().unpack(str[start:end])
        self.state.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_iIiH = None
def _get_struct_iIiH():
    global _struct_iIiH
    if _struct_iIiH is None:
        _struct_iIiH = struct.Struct("<iIiH")
    return _struct_iIiH
