; Auto-generated. Do not edit!


(cl:in-package behavior_msgs-msg)


;//! \htmlinclude MoveToJointFeedback.msg.html

(cl:defclass <MoveToJointFeedback> (roslisp-msg-protocol:ros-message)
  ((pose
    :reader pose
    :initarg :pose
    :type control_core_msgs-msg:Vector
    :initform (cl:make-instance 'control_core_msgs-msg:Vector)))
)

(cl:defclass MoveToJointFeedback (<MoveToJointFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToJointFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToJointFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_msgs-msg:<MoveToJointFeedback> is deprecated: use behavior_msgs-msg:MoveToJointFeedback instead.")))

(cl:ensure-generic-function 'pose-val :lambda-list '(m))
(cl:defmethod pose-val ((m <MoveToJointFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_msgs-msg:pose-val is deprecated.  Use behavior_msgs-msg:pose instead.")
  (pose m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToJointFeedback>) ostream)
  "Serializes a message object of type '<MoveToJointFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pose) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToJointFeedback>) istream)
  "Deserializes a message object of type '<MoveToJointFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pose) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToJointFeedback>)))
  "Returns string type for a message object of type '<MoveToJointFeedback>"
  "behavior_msgs/MoveToJointFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToJointFeedback)))
  "Returns string type for a message object of type 'MoveToJointFeedback"
  "behavior_msgs/MoveToJointFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToJointFeedback>)))
  "Returns md5sum for a message object of type '<MoveToJointFeedback>"
  "841a03b07f9c3f786f5afdf61c067d2c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToJointFeedback)))
  "Returns md5sum for a message object of type 'MoveToJointFeedback"
  "841a03b07f9c3f786f5afdf61c067d2c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToJointFeedback>)))
  "Returns full string definition for message of type '<MoveToJointFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%control_core_msgs/Vector pose~%~%================================================================================~%MSG: control_core_msgs/Vector~%float64[] data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToJointFeedback)))
  "Returns full string definition for message of type 'MoveToJointFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%control_core_msgs/Vector pose~%~%================================================================================~%MSG: control_core_msgs/Vector~%float64[] data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToJointFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pose))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToJointFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToJointFeedback
    (cl:cons ':pose (pose msg))
))
