; Auto-generated. Do not edit!


(cl:in-package behavior_msgs-msg)


;//! \htmlinclude MoveToJointGoal.msg.html

(cl:defclass <MoveToJointGoal> (roslisp-msg-protocol:ros-message)
  ((target
    :reader target
    :initarg :target
    :type control_core_msgs-msg:Vector
    :initform (cl:make-instance 'control_core_msgs-msg:Vector))
   (intermediate
    :reader intermediate
    :initarg :intermediate
    :type control_core_msgs-msg:Vector
    :initform (cl:make-instance 'control_core_msgs-msg:Vector))
   (motion_task
    :reader motion_task
    :initarg :motion_task
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String))
   (period
    :reader period
    :initarg :period
    :type std_msgs-msg:Float64
    :initform (cl:make-instance 'std_msgs-msg:Float64)))
)

(cl:defclass MoveToJointGoal (<MoveToJointGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <MoveToJointGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'MoveToJointGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name behavior_msgs-msg:<MoveToJointGoal> is deprecated: use behavior_msgs-msg:MoveToJointGoal instead.")))

(cl:ensure-generic-function 'target-val :lambda-list '(m))
(cl:defmethod target-val ((m <MoveToJointGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_msgs-msg:target-val is deprecated.  Use behavior_msgs-msg:target instead.")
  (target m))

(cl:ensure-generic-function 'intermediate-val :lambda-list '(m))
(cl:defmethod intermediate-val ((m <MoveToJointGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_msgs-msg:intermediate-val is deprecated.  Use behavior_msgs-msg:intermediate instead.")
  (intermediate m))

(cl:ensure-generic-function 'motion_task-val :lambda-list '(m))
(cl:defmethod motion_task-val ((m <MoveToJointGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_msgs-msg:motion_task-val is deprecated.  Use behavior_msgs-msg:motion_task instead.")
  (motion_task m))

(cl:ensure-generic-function 'period-val :lambda-list '(m))
(cl:defmethod period-val ((m <MoveToJointGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader behavior_msgs-msg:period-val is deprecated.  Use behavior_msgs-msg:period instead.")
  (period m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <MoveToJointGoal>) ostream)
  "Serializes a message object of type '<MoveToJointGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'intermediate) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'motion_task) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'period) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <MoveToJointGoal>) istream)
  "Deserializes a message object of type '<MoveToJointGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'intermediate) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'motion_task) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'period) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<MoveToJointGoal>)))
  "Returns string type for a message object of type '<MoveToJointGoal>"
  "behavior_msgs/MoveToJointGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'MoveToJointGoal)))
  "Returns string type for a message object of type 'MoveToJointGoal"
  "behavior_msgs/MoveToJointGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<MoveToJointGoal>)))
  "Returns md5sum for a message object of type '<MoveToJointGoal>"
  "af979f8fbb920ef78156356fc24a7d2b")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'MoveToJointGoal)))
  "Returns md5sum for a message object of type 'MoveToJointGoal"
  "af979f8fbb920ef78156356fc24a7d2b")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<MoveToJointGoal>)))
  "Returns full string definition for message of type '<MoveToJointGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%control_core_msgs/Vector target         # target joint pose~%control_core_msgs/Vector intermediate   # optional intermediate target~%std_msgs/String motion_task             # motion task for the movement~%std_msgs/Float64 period                 # time period of the motion~%~%================================================================================~%MSG: control_core_msgs/Vector~%float64[] data~%================================================================================~%MSG: std_msgs/String~%string data~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'MoveToJointGoal)))
  "Returns full string definition for message of type 'MoveToJointGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%control_core_msgs/Vector target         # target joint pose~%control_core_msgs/Vector intermediate   # optional intermediate target~%std_msgs/String motion_task             # motion task for the movement~%std_msgs/Float64 period                 # time period of the motion~%~%================================================================================~%MSG: control_core_msgs/Vector~%float64[] data~%================================================================================~%MSG: std_msgs/String~%string data~%~%================================================================================~%MSG: std_msgs/Float64~%float64 data~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <MoveToJointGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'intermediate))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'motion_task))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'period))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <MoveToJointGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'MoveToJointGoal
    (cl:cons ':target (target msg))
    (cl:cons ':intermediate (intermediate msg))
    (cl:cons ':motion_task (motion_task msg))
    (cl:cons ':period (period msg))
))
