left:
  robot_type: sim # sim / real 
  
  v_max_limit: 60 # [deg/s] 90
  q_step_limit: 5.0 # [deg]
  butterworth_f_cutoff: 20
  control_period: 2 # [ms]

  home_posture: [-162.07, -62.65, 80.36, -139.08, 55.93, -8.25] # deg

  joint_names:
    - l_shoulder_pan_joint
    - l_shoulder_lift_joint
    - l_elbow_joint
    - l_wrist_1_joint
    - l_wrist_2_joint
    - l_wrist_3_joint

# For robot communication in arm_comm_interface
communication:
  PC_ADDRESS: 192.168.1.3
  ROBOT_ADDRESS: 192.168.1.7
  PC_TRAJ_PORT: 50005
  ROBOT_STATE_PORT: 30003
  MOTION_COMMAND: VELOCITY # POSITION
  ROBOT_VERSION: 3.1