right:
  robot_type: sim # sim / real 

  v_max_limit: 60 # [deg/s] 90
  q_step_limit: 5.0 # [deg]
  butterworth_f_cutoff: 20
  control_period: 2 # [ms]

  home_posture: [161.58, -116.63, -82.21, -38.74, -57.86, 9.50] # deg

  joint_names:
    - r_shoulder_pan_joint
    - r_shoulder_lift_joint
    - r_elbow_joint
    - r_wrist_1_joint
    - r_wrist_2_joint
    - r_wrist_3_joint

  # For robot communication in arm_comm_interface
communication:
  PC_ADDRESS: 192.168.1.3
  ROBOT_ADDRESS: 192.168.1.5
  PC_TRAJ_PORT: 50002
  ROBOT_STATE_PORT: 30003
  MOTION_COMMAND: VELOCITY # POSITION
  ROBOT_VERSION: 1.8
