(cl:defpackage ur_script_manager-srv
  (:use )
  (:export
   "GETSCRIPTMANAGERSTATES"
   "<GETSCRIPTMANAGERSTATES-REQUEST>"
   "GETSCRIPTMANAGERSTATES-REQUEST"
   "<GETSCRIPTMANAGERSTATES-RESPONSE>"
   "GETSCRIPTMANAGERSTATES-RESPONSE"
   "SETSCRIPTMANAGERSTATE"
   "<SETSCRIPTMANAGERSTATE-REQUEST>"
   "SETSCRIPTMANAGERSTATE-REQUEST"
   "<SETSCRIPTMANAGERSTATE-RESPONSE>"
   "SETSCRIPTMANAGERSTATE-RESPONSE"
  ))

