(cl:defpackage behavior_msgs-srv
  (:use )
  (:export
   "CHANGEBEHAVIOR"
   "<CHANGEBEHAVIOR-REQUEST>"
   "CHANGEBEHAVIOR-REQUEST"
   "<CHANGEBEHAVIOR-RESPONSE>"
   "CHANGEBEHAVIOR-RESPONSE"
   "CHANGECONTACT"
   "<CHANGECONTACT-REQUEST>"
   "CHANGECONTACT-REQUEST"
   "<CHANGECONTACT-RESPONSE>"
   "CHANGECONTACT-RESPONSE"
   "LISTBEHAVIOR"
   "<LISTBEHAVIOR-REQUEST>"
   "LISTBEHAVIOR-REQUEST"
   "<LISTBEHAVIOR-RESPONSE>"
   "LISTBEHAVIOR-RESPONSE"
  ))

